# This docker-compose file is not designed to run
# Usage: Build & Push

version: '3.5'

services:
  cicd:
    image: lappis/gitlab-ci-cd:latest
    build:
      context: ../../
      dockerfile: ./docker/cicd/dind/Dockerfile
